SAMPLE_JOBS = [

    {
        "source_job_id": "MS-001",
        "title": "Python Developer",
        "slug": "python-developer-ms001",
        "description": "Develop backend applications using Python, Flask and PostgreSQL.",
        "company_name": "Microsoft",
        "job_source_name": "Company Careers",
        "job_source_type": "company",
        "category": "Software Development",
        "industry": "IT",
        "skills": "Python, Flask, PostgreSQL",
        "country": "India",
        "state": "Telangana",
        "city": "Hyderabad",
        "remote": True,
        "experience_level": "Mid Level",
        "experience_min": 2,
        "experience_max": 5,
        "employment_type": "Full Time",
        "salary_min": 800000,
        "salary_max": 1200000,
        "salary_type": "Yearly",
        "currency": "INR",
        "apply_url": "https://careers.microsoft.com/",
        "status": "published",
        "is_active": True
    },

    {
        "source_job_id": "GG-001",
        "title": "Software Engineer",
        "slug": "software-engineer-gg001",
        "description": "Build scalable cloud applications.",
        "company_name": "Google",
        "job_source_name": "Company Careers",
        "job_source_type": "company",
        "category": "Software Development",
        "industry": "IT",
        "skills": "Java, Go, Cloud",
        "country": "India",
        "state": "Karnataka",
        "city": "Bengaluru",
        "remote": False,
        "experience_level": "Mid Level",
        "experience_min": 3,
        "experience_max": 6,
        "employment_type": "Full Time",
        "salary_min": 1800000,
        "salary_max": 2800000,
        "salary_type": "Yearly",
        "currency": "INR",
        "apply_url": "https://careers.google.com/",
        "status": "published",
        "is_active": True
    },

    {
        "source_job_id": "AMZ-001",
        "title": "Cloud Engineer",
        "slug": "cloud-engineer-amz001",
        "description": "Manage AWS cloud infrastructure.",
        "company_name": "Amazon",
        "job_source_name": "Company Careers",
        "job_source_type": "company",
        "category": "Cloud",
        "industry": "IT",
        "skills": "AWS, Linux, Terraform",
        "country": "India",
        "state": "Telangana",
        "city": "Hyderabad",
        "remote": False,
        "experience_level": "Senior",
        "experience_min": 5,
        "experience_max": 8,
        "employment_type": "Full Time",
        "salary_min": 1500000,
        "salary_max": 2400000,
        "salary_type": "Yearly",
        "currency": "INR",
        "apply_url": "https://www.amazon.jobs/",
        "status": "published",
        "is_active": True
    },

    {
        "source_job_id": "APL-001",
        "title": "iOS Developer",
        "slug": "ios-developer-apl001",
        "description": "Develop iOS applications using Swift.",
        "company_name": "Apple",
        "job_source_name": "Company Careers",
        "job_source_type": "company",
        "category": "Mobile",
        "industry": "IT",
        "skills": "Swift, UIKit",
        "country": "India",
        "state": "Karnataka",
        "city": "Bengaluru",
        "remote": True,
        "experience_level": "Mid Level",
        "experience_min": 3,
        "experience_max": 5,
        "employment_type": "Full Time",
        "salary_min": 1800000,
        "salary_max": 2600000,
        "salary_type": "Yearly",
        "currency": "INR",
        "apply_url": "https://jobs.apple.com/",
        "status": "published",
        "is_active": True
    },

    {
        "source_job_id": "META-001",
        "title": "React Developer",
        "slug": "react-developer-meta001",
        "description": "Build modern React web applications.",
        "company_name": "Meta",
        "job_source_name": "Company Careers",
        "job_source_type": "company",
        "category": "Frontend",
        "industry": "IT",
        "skills": "React, JavaScript",
        "country": "India",
        "state": "Telangana",
        "city": "Hyderabad",
        "remote": True,
        "experience_level": "Mid Level",
        "experience_min": 2,
        "experience_max": 5,
        "employment_type": "Full Time",
        "salary_min": 1400000,
        "salary_max": 2200000,
        "salary_type": "Yearly",
        "currency": "INR",
        "apply_url": "https://www.metacareers.com/",
        "status": "published",
        "is_active": True
    }

]