"""add recent jobs

Revision ID: 838dc90973ca
Revises: 0c8fb48603f8
Create Date: 2026-06-29 15:39:31.295049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838dc90973ca'
down_revision = '0c8fb48603f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recent_jobs')
    # ### end Alembic commands ###
