"""add resume model

Revision ID: af60027c2cec
Revises: edf7a72456f9
Create Date: 2026-06-29 12:37:40.538324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af60027c2cec'
down_revision = 'edf7a72456f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.drop_column('ats_score')
        batch_op.drop_column('resume_file')
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('resume_file', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('ats_score', sa.FLOAT(), nullable=True))
        batch_op.drop_column('education')
        batch_op.drop_column('experience')
        batch_op.drop_column('skills')
        batch_op.drop_column('summary')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
