WORKDAY_COMPANIES = [
    ("accenture", "Accenture"),
    ("dell", "Dell Technologies"),
    ("boeing", "Boeing"),
    ("capitalone", "Capital One"),
    ("target", "Target"),
    ("nike", "Nike"),
    ("vmware", "VMware"),
    ("nvidia", "NVIDIA"),
    ("google", "Google"),
    ("microsoft", "Microsoft"),
    ("amazon", "Amazon"),
    ("apple", "Apple"),
    ("meta", "Meta"),
    ("adobe", "Adobe"),
    ("oracle", "Oracle"),
    ("ibm", "IBM"),
    ("cisco", "Cisco"),
    ("intel", "Intel"),
    ("salesforce", "Salesforce"),
    ("uber", "Uber"),
    ("lyft", "Lyft"),
    ("airbnb", "Airbnb"),
    ("spotify", "Spotify"),
    ("netflix", "Netflix"),
]